[package]
name = "pumpfun-idl"
version = "0.1.0"
edition = "2025"

[features]
default = ["cpi"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-gen = "0.3.0"
anchor-lang = ">=0.20"
